Разметка
htmlacademy-adaptive/2018629-cat-energy-26 pull request #2
Opened 2022-08-13 16:30 UTC by Sephellone

2022-08-14 06:59 UTC, VAnastasia requested changes

2022-08-14 06:59 UTC, VAnastasia commented on source/form.html
> +                <span class="chekbox-control__label">питьевая вода</span>
нет блока chekbox-control

2022-08-14 06:59 UTC, VAnastasia commented on source/index.html
> +        <img class="main-header__logo-text" src="img/logo-mobile-text.svg" width="101" height="18" alt="Магазин «CAT ENERGY».">
alt должен быть у всех img

2022-08-14 06:59 UTC, VAnastasia commented on source/index.html
> +        <!--Не знаю, как вставить карту без всех управляющих элементов на ней, поэтому пока вставила так-->
управляющие элементы на карте нужны, не надо их убирать

2022-08-14 06:59 UTC, VAnastasia commented on source/index.html
> +              Не знаю, как правильно, поэтому пока тут тоже ренж-слайдер. -->
input type="range" сложно стилизовать, обычно используют разные библиотеки для реализации подобного слайдера, по ТЗ логику слайдера реализовывать не обязательно, достаточно вёрстки, соответствующей макету

2022-08-15 07:58 UTC, Sephellone commented on source/form.html
> +                <span class="chekbox-control__label">питьевая вода</span>
Забыла переименовать класс после копирования блока. Теперь исправлено.

2022-08-15 07:59 UTC, Sephellone commented on source/index.html
> +              <input class="range-slider__toggle" type="checkbox">
Изменила ренж слайдер на чекбокс, поскольку как его стилизовать под то, что нарисовано в макете мобильной версии, мне понятно

2022-08-15 08:19 UTC, merged